import { useMutation, useQuery } from "@tanstack/react-query";
import { Bell, Clock, MapPin, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useState } from "react";
import { useLocation } from "wouter";

type Region = { id: string; name: string; countryCode: string; type: string };
type Organisation = { id: string; name: string };
type Assignment = { id: string; regionId: string; regionName: string; regionCode: string; countryCode: string; canPublish: boolean; canFulfil: boolean; status?: string };
type Opportunity = { id: string; productName: string; regionId: string; regionName: string; categoryId: string; subcategoryId: string; status: string; claimedBy: string | null; claimExpiresAt: string | null };
type Notification = { id: string; title: string; message: string; readAt: string | null; createdAt: string };

export function SellerRegionalMarketplace() {
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const [regionId, setRegionId] = useState("");
  const [organisationId, setOrganisationId] = useState("agriconnect");
  const { data: regions = [] } = useQuery<Region[]>({ queryKey: ["/api/marketplace/regions"] });
  const { data: assignments = [] } = useQuery<Assignment[]>({ queryKey: ["/api/seller/regions"] });
  const organisationEndpoint = `/api/marketplace/regions/${regionId}/organisations`;
  const { data: organisations = [] } = useQuery<Organisation[]>({ queryKey: [organisationEndpoint], enabled: Boolean(regionId) });
  const { data: opportunities = [] } = useQuery<Opportunity[]>({ queryKey: ["/api/seller/opportunities"] });
  const { data: notifications = [] } = useQuery<Notification[]>({ queryKey: ["/api/marketplace/notifications"] });
  const requestRegion = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/seller/regions/request", { regionId, ...(organisationId !== "agriconnect" ? { organisationId } : {}) })).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/seller/regions"] }); toast({ title: "Regional approval requested" }); setRegionId(""); setOrganisationId("agriconnect"); }, onError: () => toast({ title: "Unable to request region", variant: "destructive" }) });
  const claim = useMutation({ mutationFn: async (id: string) => (await apiRequest("POST", `/api/seller/opportunities/${id}/claim`)).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/seller/opportunities"] }); toast({ title: "Opportunity reserved for you" }); }, onError: () => { queryClient.invalidateQueries({ queryKey: ["/api/seller/opportunities"] }); toast({ title: "Opportunity is no longer available", variant: "destructive" }); } });
  const cancel = useMutation({ mutationFn: async (id: string) => apiRequest("POST", `/api/seller/opportunities/${id}/cancel`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/seller/opportunities"] }) });
  return <div className="space-y-5">
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="h-5 w-5 text-emerald-600" />Approved selling regions</CardTitle><p className="text-sm text-muted-foreground">You may publish and fulfil products only in regions approved by AgriConnect or an authorised regional organisation.</p></CardHeader><CardContent className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-2">{assignments.map((assignment) => <div key={assignment.id} className="rounded-xl border p-3"><div className="flex items-center justify-between"><strong>{assignment.regionName}</strong><Badge className={assignment.canPublish ? "bg-emerald-600" : ""}>{assignment.canPublish ? "active" : assignment.status || "pending"}</Badge></div><p className="text-xs text-muted-foreground">{assignment.regionCode} Â· {assignment.countryCode}</p><div className="mt-2 flex gap-2 text-xs"><span>{assignment.canPublish ? "Can publish" : "Publishing pending"}</span><span>Â·</span><span>{assignment.canFulfil ? "Can fulfil" : "Fulfilment pending"}</span></div></div>)}{assignments.length === 0 && <p className="text-sm text-muted-foreground">No selling regions have been assigned yet.</p>}</div>
      <div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Select value={regionId} onValueChange={(value) => { setRegionId(value); setOrganisationId("agriconnect"); }}><SelectTrigger><SelectValue placeholder="Request another region" /></SelectTrigger><SelectContent>{regions.filter((region) => !["country", "state", "province"].includes(region.type)).map((region) => <SelectItem key={region.id} value={region.id}>{region.name}, {region.countryCode}</SelectItem>)}</SelectContent></Select><Select value={organisationId} onValueChange={setOrganisationId} disabled={!regionId}><SelectTrigger><SelectValue placeholder="Approval authority" /></SelectTrigger><SelectContent><SelectItem value="agriconnect">AgriConnect review</SelectItem>{organisations.map((organisation) => <SelectItem key={organisation.id} value={organisation.id}>{organisation.name}</SelectItem>)}</SelectContent></Select><Button disabled={!regionId || requestRegion.isPending} onClick={() => requestRegion.mutate()}>Request approval</Button></div>
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-amber-600" />Regional opportunities</CardTitle><p className="text-sm text-muted-foreground">Missing products are offered to eligible sellers one at a time. Complete the listing before the reservation expires.</p></CardHeader><CardContent className="space-y-3">{opportunities.map((opportunity) => <div key={opportunity.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><div className="font-black">Opportunity Available: {opportunity.productName}</div><p className="text-sm text-muted-foreground">Not currently listed in {opportunity.regionName}.</p>{opportunity.claimExpiresAt && <p className="mt-1 flex items-center gap-1 text-xs text-amber-700"><Clock className="h-3 w-3" />Reserved until {new Date(opportunity.claimExpiresAt).toLocaleString()}</p>}</div>{opportunity.status === "open" ? <Button disabled={claim.isPending} onClick={() => claim.mutate(opportunity.id)}>Accept opportunity</Button> : <div className="flex gap-2"><Button onClick={() => navigate(`/dashboard/list-product?opportunityId=${encodeURIComponent(opportunity.id)}&productName=${encodeURIComponent(opportunity.productName)}&regionId=${encodeURIComponent(opportunity.regionId)}&categoryId=${encodeURIComponent(opportunity.categoryId)}&subcategoryId=${encodeURIComponent(opportunity.subcategoryId)}`)}>Create listing</Button><Button variant="outline" disabled={cancel.isPending} onClick={() => cancel.mutate(opportunity.id)}>Release opportunity</Button></div>}</div>)}{opportunities.length === 0 && <p className="text-sm text-muted-foreground">No opportunities are currently available in your approved regions.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Bell className="h-5 w-5 text-blue-600" />Marketplace notifications</CardTitle></CardHeader><CardContent className="space-y-2">{notifications.slice(0, 10).map((notification) => <button key={notification.id} className={`block w-full rounded-lg border p-3 text-left ${notification.readAt ? "opacity-70" : "border-blue-300 bg-blue-50/50"}`} onClick={async () => { await apiRequest("POST", `/api/marketplace/notifications/${notification.id}/read`); queryClient.invalidateQueries({ queryKey: ["/api/marketplace/notifications"] }); }}><strong className="text-sm">{notification.title}</strong><p className="text-xs text-muted-foreground">{notification.message}</p></button>)}{notifications.length === 0 && <p className="text-sm text-muted-foreground">No regional marketplace notifications yet.</p>}</CardContent></Card>
  </div>;
}
