import type { LogisticsPartner, LandListing, MilkRunRoute, UrgentOrder, GovernmentLandProgram, LeaseAgreement } from "@shared/schema";

export const logisticsPartners: LogisticsPartner[] = [
  {
    id: "dhl-express",
    name: "DHL Express",
    type: "international",
    coverage: "190+ countries worldwide",
    rating: 4.7,
    deliveryCount: 125000,
    features: ["Express delivery", "Real-time tracking", "Customs clearance", "Insurance"],
    priceRange: "12.99-45.99",
    deliveryTime: "2-5 days",
    coldChain: false,
    tracking: true,
    insurance: true,
  },
  {
    id: "fedex-intl",
    name: "FedEx International",
    type: "international",
    coverage: "220+ countries worldwide",
    rating: 4.6,
    deliveryCount: 98000,
    features: ["Priority shipping", "Saturday delivery", "Packaging services"],
    priceRange: "14.99-52.99",
    deliveryTime: "2-6 days",
    coldChain: false,
    tracking: true,
    insurance: true,
  },
  {
    id: "ups-worldwide",
    name: "UPS Worldwide",
    type: "international",
    coverage: "220+ countries worldwide",
    rating: 4.5,
    deliveryCount: 87000,
    features: ["Express saver", "Time-definite delivery", "Proof of delivery"],
    priceRange: "11.99-48.99",
    deliveryTime: "3-7 days",
    coldChain: false,
    tracking: true,
    insurance: true,
  },
  {
    id: "royal-mail",
    name: "Royal Mail",
    type: "national",
    coverage: "UK-wide, 30M+ addresses",
    rating: 4.4,
    deliveryCount: 250000,
    features: ["Next-day delivery", "Tracked 24/48", "Special delivery"],
    priceRange: "3.99-12.99",
    deliveryTime: "1-3 days",
    coldChain: false,
    tracking: true,
    insurance: true,
  },
  {
    id: "dpd-uk",
    name: "DPD UK",
    type: "national",
    coverage: "UK-wide delivery network",
    rating: 4.6,
    deliveryCount: 180000,
    features: ["One-hour delivery window", "In-flight parcel changes", "Pickup points"],
    priceRange: "4.99-15.99",
    deliveryTime: "1-2 days",
    coldChain: false,
    tracking: true,
    insurance: true,
  },
  {
    id: "evri",
    name: "Evri (Hermes)",
    type: "national",
    coverage: "UK-wide, 13,000+ ParcelShops",
    rating: 4.2,
    deliveryCount: 320000,
    features: ["Economical shipping", "ParcelShop collection", "Photo proof"],
    priceRange: "2.99-8.99",
    deliveryTime: "2-5 days",
    coldChain: false,
    tracking: true,
    insurance: false,
  },
  {
    id: "deliveroo-fresh",
    name: "Deliveroo Fresh",
    type: "hyperlocal",
    coverage: "Major UK cities (50+ cities)",
    rating: 4.5,
    deliveryCount: 45000,
    features: ["Same-day delivery", "Live GPS tracking", "Contactless"],
    priceRange: "2.99-6.99",
    deliveryTime: "30-90 mins",
    coldChain: true,
    tracking: true,
    insurance: false,
  },
  {
    id: "stuart",
    name: "Stuart Delivery",
    type: "hyperlocal",
    coverage: "UK major cities",
    rating: 4.4,
    deliveryCount: 38000,
    features: ["On-demand delivery", "API integration", "B2B specialist"],
    priceRange: "4.99-12.99",
    deliveryTime: "1-3 hours",
    coldChain: false,
    tracking: true,
    insurance: false,
  },
  {
    id: "cold-chain-uk",
    name: "Cold Chain UK",
    type: "cold-chain",
    coverage: "UK-wide temperature-controlled",
    rating: 4.8,
    deliveryCount: 15000,
    features: ["Temperature monitoring", "Pharma-grade cold chain", "HACCP certified"],
    priceRange: "15.99-45.99",
    deliveryTime: "24-48 hours",
    coldChain: true,
    tracking: true,
    insurance: true,
  },
  {
    id: "freshlinc",
    name: "FreshLinc",
    type: "cold-chain",
    coverage: "UK & Europe temperature logistics",
    rating: 4.7,
    deliveryCount: 22000,
    features: ["Multi-temp vehicles", "Farm-to-fork tracking", "Food safety certified"],
    priceRange: "12.99-38.99",
    deliveryTime: "Same-day to 48 hours",
    coldChain: true,
    tracking: true,
    insurance: true,
  },
  {
    id: "maersk",
    name: "Maersk",
    type: "freight",
    coverage: "Global ocean freight, 343 ports",
    rating: 4.6,
    deliveryCount: 8500,
    features: ["Container shipping", "Reefer containers", "Supply chain solutions"],
    priceRange: "Custom quote",
    deliveryTime: "15-45 days",
    coldChain: true,
    tracking: true,
    insurance: true,
  },
  {
    id: "db-schenker",
    name: "DB Schenker",
    type: "freight",
    coverage: "Multimodal - air, sea, road, rail",
    rating: 4.5,
    deliveryCount: 12000,
    features: ["Contract logistics", "Warehouse solutions", "Customs brokerage"],
    priceRange: "Custom quote",
    deliveryTime: "5-30 days",
    coldChain: true,
    tracking: true,
    insurance: true,
  },
];

export const sampleLandListings: LandListing[] = [
  {
    id: "land-001",
    ownerId: "owner-1",
    ownerName: "James Wilson",
    ownerPhone: "+44 7700 900123",
    title: "15 Acres Premium Black Soil Land",
    description: "Excellent agricultural land with rich black soil, ideal for vegetable cultivation. Borewell available with drip irrigation setup. Road access and electricity connection available.",
    type: "agricultural",
    area: 15,
    areaUnit: "acres",
    location: "Oxfordshire, UK",
    latitude: 51.8157,
    longitude: -1.2577,
    soilType: "Black Soil",
    topography: "flat",
    condition: "fallow",
    waterSources: ["Borewell", "Drip Irrigation"],
    infrastructure: ["Electricity", "Road Access", "Storage Shed"],
    rentPerMonth: 800,
    deposit: 2400,
    minLeaseDuration: 12,
    permissions: ["Crops allowed", "Organic farming mandatory"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.8,
    reviewCount: 23,
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-002",
    ownerId: "owner-2",
    ownerName: "Sarah Thompson",
    title: "8 Acres Irrigated Farmland",
    description: "Well-irrigated farmland with canal access and sprinkler system. Previously used for wheat cultivation. Excellent water availability year-round.",
    type: "irrigated",
    area: 8,
    areaUnit: "acres",
    location: "Norfolk, UK",
    latitude: 52.6309,
    longitude: 1.2974,
    soilType: "Loamy Soil",
    topography: "flat",
    condition: "cultivated",
    waterSources: ["Canal Irrigation", "Sprinkler System", "Rainwater Harvesting"],
    infrastructure: ["Electricity", "Road Access", "Fencing"],
    rentPerMonth: 600,
    deposit: 1800,
    minLeaseDuration: 6,
    permissions: ["All crops allowed", "Livestock allowed"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.6,
    reviewCount: 15,
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-003",
    ownerId: "owner-3",
    ownerName: "Michael Brown",
    title: "25 Acres Organic Certified Zone",
    description: "Certified organic farmland perfect for premium produce. Complete organic certification with soil health reports. Ideal for farmers looking to grow organic vegetables and fruits.",
    type: "specialty",
    area: 25,
    areaUnit: "acres",
    location: "Somerset, UK",
    latitude: 51.1050,
    longitude: -2.9262,
    soilType: "Clay Loam",
    topography: "gentle-slope",
    condition: "fallow",
    waterSources: ["Borewell", "River nearby"],
    infrastructure: ["Electricity", "Farm House", "Storage Barn", "Road Access"],
    rentPerMonth: 1200,
    deposit: 3600,
    minLeaseDuration: 24,
    permissions: ["Organic farming only", "No pesticides", "Soil testing required"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.9,
    reviewCount: 31,
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-004",
    ownerId: "owner-4",
    ownerName: "Government Land Bank",
    title: "PM-KISAN Land Bank Plot",
    description: "Government subsidized agricultural land available under PM-KISAN scheme. Priority given to young farmers aged 18-35. Training and seed support included.",
    type: "government",
    area: 5,
    areaUnit: "acres",
    location: "Lincolnshire, UK",
    latitude: 53.2344,
    longitude: -0.5379,
    soilType: "Sandy Loam",
    topography: "flat",
    condition: "barren",
    waterSources: ["Borewell planned"],
    infrastructure: ["Road Access"],
    rentPerMonth: 100,
    deposit: 300,
    minLeaseDuration: 60,
    permissions: ["Training mandatory", "Progress reporting required"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.5,
    reviewCount: 45,
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-005",
    ownerId: "owner-5",
    ownerName: "Emily Clarke",
    title: "3 Acres Greenhouse Site",
    description: "Perfect location for greenhouse/polyhouse setup. All utilities available. Previous greenhouse structure foundation in place. Ideal for hydroponics or vertical farming.",
    type: "specialty",
    area: 3,
    areaUnit: "acres",
    location: "Kent, UK",
    latitude: 51.2787,
    longitude: 1.0803,
    soilType: "Mixed",
    topography: "flat",
    condition: "fallow",
    waterSources: ["Mains Water", "Rainwater Collection"],
    infrastructure: ["Electricity", "Road Access", "Foundation", "Water Tank"],
    rentPerMonth: 450,
    deposit: 1350,
    minLeaseDuration: 12,
    permissions: ["Construction allowed", "Greenhouse setup allowed"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.7,
    reviewCount: 12,
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-006",
    ownerId: "owner-6",
    ownerName: "Robert Hughes",
    title: "Seasonal Crop Land - 6 Month Lease",
    description: "Available for seasonal crop cultivation. Perfect for trial farming or seasonal vegetables. Previous successful yields of tomatoes and peppers.",
    type: "short-term",
    area: 4,
    areaUnit: "acres",
    location: "Cambridgeshire, UK",
    latitude: 52.2053,
    longitude: 0.1218,
    soilType: "Alluvial",
    topography: "flat",
    condition: "cultivated",
    waterSources: ["Drip Irrigation", "Borewell"],
    infrastructure: ["Electricity", "Road Access", "Tool Shed"],
    rentPerMonth: 350,
    deposit: 700,
    minLeaseDuration: 3,
    permissions: ["Seasonal crops only", "No permanent structures"],
    images: [],
    isVerified: true,
    isAvailable: true,
    rating: 4.4,
    reviewCount: 28,
    createdAt: new Date().toISOString(),
  },
];

export const milkRunRoutes: MilkRunRoute[] = [
  {
    id: "route-001",
    name: "Route 1 - South England",
    vehicle: "Cold Chain Vehicle",
    vehicleNumber: "UK-01-AB-1234",
    driver: "John Smith",
    driverPhone: "+44 7700 900456",
    capacity: 500,
    capacityUnit: "kg",
    usedCapacity: 160,
    temperature: -2,
    pickups: [
      { time: "6:00 AM", farmer: "Wilson Farm", items: "50kg tomatoes", location: "Oxfordshire", status: "completed" },
      { time: "6:25 AM", farmer: "Green Valley", items: "30kg spinach", location: "Buckinghamshire", status: "completed" },
      { time: "6:50 AM", farmer: "Happy Harvest", items: "80kg carrots", location: "Berkshire", status: "in-progress" },
    ],
    deliveries: [
      { time: "9:30 AM", buyer: "Fresh Foods Ltd", items: "70kg mixed", location: "Reading", status: "pending" },
      { time: "10:15 AM", buyer: "Organic Mart", items: "90kg mixed", location: "Slough", status: "pending" },
    ],
    costPerFarmer: 8,
    individualCost: 25,
    savings: 68,
    efficiency: 85,
    carbonReduction: 75,
    totalTime: "5 hours",
    status: "in-progress",
  },
  {
    id: "route-002",
    name: "Route 2 - East Midlands",
    vehicle: "Standard Vehicle",
    vehicleNumber: "UK-02-CD-5678",
    driver: "Mike Johnson",
    driverPhone: "+44 7700 900789",
    capacity: 800,
    capacityUnit: "kg",
    usedCapacity: 200,
    temperature: null,
    pickups: [
      { time: "5:30 AM", farmer: "Sunrise Farm", items: "100kg potatoes", location: "Lincolnshire", status: "completed" },
      { time: "6:15 AM", farmer: "Hill Top", items: "60kg onions", location: "Nottinghamshire", status: "completed" },
      { time: "7:00 AM", farmer: "River View", items: "40kg peppers", location: "Leicestershire", status: "pending" },
    ],
    deliveries: [
      { time: "9:00 AM", buyer: "City Grocers", items: "120kg mixed", location: "Nottingham", status: "pending" },
      { time: "10:00 AM", buyer: "Market Fresh", items: "80kg mixed", location: "Leicester", status: "pending" },
    ],
    costPerFarmer: 6,
    individualCost: 20,
    savings: 70,
    efficiency: 78,
    carbonReduction: 72,
    totalTime: "4.5 hours",
    status: "in-progress",
  },
];

export const urgentOrders: UrgentOrder[] = [
  {
    id: "urgent-001",
    buyer: "Hotel Taj",
    product: "potatoes",
    quantity: 50,
    unit: "kg",
    deliveryBy: "10:00 AM",
    location: "London",
    revenue: 1200,
    status: "pending",
  },
  {
    id: "urgent-002",
    buyer: "Restaurant Chain",
    product: "tomatoes",
    quantity: 30,
    unit: "kg",
    deliveryBy: "11:00 AM",
    location: "Oxford",
    revenue: 850,
    status: "pending",
  },
];

export const governmentLandPrograms: GovernmentLandProgram[] = [
  {
    id: "gov-001",
    name: "PM-KISAN Land Bank",
    description: "50,000 acres available across UK. Priority to youth farmers (18-35 years).",
    acresAvailable: 50000,
    subsidizedRent: 100,
    leaseTerm: "5-year lease with renewal option",
    benefits: ["Training included", "Seed support", "Priority access"],
    eligibility: ["Youth farmers 18-35", "First-time farmers", "Low-income households"],
  },
  {
    id: "gov-002",
    name: "Wasteland Development",
    description: "Barren/degraded land rehabilitation program.",
    acresAvailable: 25000,
    subsidizedRent: 0,
    leaseTerm: "First 2 years rent-free",
    benefits: ["Soil improvement subsidy £25,000/acre", "Organic certification support", "Technical assistance"],
    eligibility: ["Registered farmers", "Environmental commitment", "Rehabilitation plan required"],
  },
  {
    id: "gov-003",
    name: "Community Farming Initiative",
    description: "Cooperative land banks for group farming projects.",
    acresAvailable: 15000,
    subsidizedRent: 50,
    leaseTerm: "3-10 year flexible terms",
    benefits: ["Group purchasing discounts", "Shared equipment", "Market access support"],
    eligibility: ["Farmer cooperatives", "Minimum 5 members", "Business plan required"],
  },
];

export const sampleLeases: LeaseAgreement[] = [
  {
    id: "lease-001",
    landId: "land-001",
    lesseeId: "farmer-1",
    lesseeName: "Rajesh Kumar",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    monthlyRent: 800,
    depositPaid: 2400,
    status: "active",
    payments: [
      { id: "pay-001", month: "January 2025", amount: 800, status: "paid", paidDate: "2025-01-05" },
      { id: "pay-002", month: "February 2025", amount: 800, status: "paid", paidDate: "2025-02-03" },
      { id: "pay-003", month: "March 2025", amount: 800, status: "pending" },
    ],
    activityLog: [
      { id: "act-001", date: "2025-03-10", description: "Soil testing completed", type: "inspection" },
      { id: "act-002", date: "2025-02-25", description: "Tomato planting started", type: "activity" },
      { id: "act-003", date: "2025-02-10", description: "Drip irrigation installed", type: "activity" },
      { id: "act-004", date: "2025-01-05", description: "First rent payment received", type: "payment" },
    ],
  },
];
